#include "msg.h"
#include <stdio.h>
#include <stdlib.h>
#include "colors.h"

// - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

void PrintWarning(char *s)
  {
  fprintf(stderr, "%s[x] Error: %s%s\n", error_color, s, normal_color);
  }

// - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

void PrintMessage(char *s)
  {
  fprintf(stderr, "%s[>] %s%s\n", normal_color, s, normal_color);
  }

void ModelsExplanation(void){
  fprintf(stderr,
  "                                                                         \n"
  "      -m <c>:<d>:<i>:<m/e>  reference model (ex: -m 13:20:1:0/0),        \n"
  "      -m <c>:<d>:<i>:<m/e>  reference model (ex: -m 18:500:1:5/50),      \n"
  "      ...                                                                \n"
  "                 templates use <c> for context-order size, <d> for       \n"
  "                 alpha (1/<d>), <i> (0 or 1) to set the usage of         \n"
  "                 inverted repeats (set 1 to use) and <m> to the          \n"
  "                 maximum allowed mutation on the context without         \n"
  "                 being discarded (usefull in deep contexts), under       \n"
  "                 the estimator <e>.                                      \n"
  "                                                                         \n");
  }

void PrintMainMenu(void)
  {
  fprintf(stderr,
  "                                                                         \n"
  "      ███████╗ █████╗ ██╗      ██████╗ ██████╗ ███╗   ██╗██████╗         \n"
  "      ██╔════╝██╔══██╗██║     ██╔════╝██╔═══██╗████╗  ██║╚════██╗        \n"
  "      █████╗  ███████║██║     ██║     ██║   ██║██╔██╗ ██║ █████╔╝        \n"
  "      ██╔══╝  ██╔══██║██║     ██║     ██║   ██║██║╚██╗██║██╔═══╝         \n"
  "      ██║     ██║  ██║███████╗╚██████╗╚██████╔╝██║ ╚████║███████╗        \n"
  "      ╚═╝     ╚═╝  ╚═╝╚══════╝ ╚═════╝ ╚═════╝ ╚═╝  ╚═══╝╚══════╝        \n"
  "                                                                         \n"
  "NAME                                                                     \n"
  "  FALCON2 v%u.%u - An ultra-fast tool to infer metagenomic composition.  \n"
  "                                                                         \n"
  "SYNOPSIS                                                                 \n"
  "      FALCON2 <command> [options]                                        \n"
  "                                                                         \n"
  "COMMANDS                                                                 \n"
  "      meta     - Infer metagenomic sample composition                    \n"
  "                 (Main FALCON functionality)                             \n"
  "      filter   - Filter and segment regions identified by FALCON         \n"
  "                 (Previously falcon-filter)                              \n"
  "      fvisual  - Create visualization of filtered regions                \n"
  "                 (Previously falcon-filter-visual)                       \n"
  "      inter    - Evaluate similarity of genomes                          \n"
  "                 (Previously falcon-inter)                               \n"
  "      ivisual  - Create heatmap visualization of genome similarities     \n"
  "                 (Previously falcon-inter-visual)                        \n"
  "                                                                         \n"
  "      Use 'FALCON2 <command> -h' for help with a specific command.       \n"
  "                                                                         \n"
  "EXAMPLES                                                                 \n"
  "      FALCON2 meta -v -F -l 47 -Z -y pro.com reads1.fq:reads2.fq DB.fa   \n"
  "      FALCON2 filter -v -F -t 1.0 -o seg.txt pro.com                     \n"
  "      FALCON2 fvisual -v -F -o map.svg seg.txt                           \n"
  "      FALCON2 inter -v file1.fa:file2.fa                                 \n"
  "      FALCON2 ivisual -F -l lab.txt -o mat.svg mat.txt                   \n"
  "                                                                         \n"
  "COPYRIGHT                                                                \n"
  "      Copyright (C) 2014-2025, IEETA, University of Aveiro.              \n"
  "      This is a Free software, under GPLv3. You may redistribute         \n"
  "      copies of it under the terms of the GNU - General Public           \n"
  "      License v3 <http://www.gnu.org/licenses/gpl.html>.                 \n"
  "                                                                         \n",
  VERSION, RELEASE);
  }

void PrintMenuFalcon(void){
  fprintf(stderr,
  "                                                                         \n"
  "                                                                         \n"
  "      ███████╗ █████╗ ██╗      ██████╗ ██████╗ ███╗   ██╗██████╗         \n"
  "      ██╔════╝██╔══██╗██║     ██╔════╝██╔═══██╗████╗  ██║╚════██╗        \n"
  "      █████╗  ███████║██║     ██║     ██║   ██║██╔██╗ ██║ █████╔╝        \n"
  "      ██╔══╝  ██╔══██║██║     ██║     ██║   ██║██║╚██╗██║██╔═══╝         \n"
  "      ██║     ██║  ██║███████╗╚██████╗╚██████╔╝██║ ╚████║███████╗        \n"
  "      ╚═╝     ╚═╝  ╚═╝╚══════╝ ╚═════╝ ╚═════╝ ╚═╝  ╚═══╝╚══════╝        \n"
  "                                                                         \n"
  "NAME                                                                     \n"
  "      FALCON2 v%u.%u: a tool to infer metagenomic composition.           \n"
  "                                                                         \n"
  "SYNOPSIS                                                                 \n"
  "      FALCON2 meta [OPTION]... [FILE1]:[FILE2]:... [FILE1]:[FILE2]:...   \n"
  "                                                                         \n"
  "SAMPLE                                                                   \n"
  "      FALCON2 meta -v -F -l 47 -Z -y pro.com reads1.fq:reads2.fq DB.fa   \n"
  "                                                                         \n"
  "DESCRIPTION                                                              \n"
  "      It infers metagenomic sample composition of sequenced reads.       \n"
  "      The core of the method uses a cooperation between multiple         \n"
  "      context and tolerant context models with several depths.           \n"
  "      The reference sequences must be in a multi-FASTA format.           \n"
  "      The sequenced reads must be trimmed and in FASTQ format.           \n"
  "                                                                         \n"
  "      Non-mandatory arguments:                                           \n"
  "                                                                         \n"
  "      -h, --help                   show this help message                \n"
  "      -F, --force                  overwrite output files                \n"
  "      -V, --version                display version and exit,             \n"
  "      -v, --verbose                verbose mode (more information),      \n"
  "      -Z, --local                  database local similarity,            \n"
  "      -s, --show                   show compression levels,              \n"
  "                                                                         \n"
  "      -l, --level <level>          compression level [%u;%u],            \n"
  "      -p, --sample <rate>          subsampling (default: %u),            \n"
  "      -t, --top <num>              top of similarity (default: %u),      \n"
  "      -n, --nThreads <num>         number of threads (default: %u),      \n"
  "                                                                         \n"
  "      -x, --output <file>          similarity top filename,              \n"
  "      -y, --profile <file>         profile filename (-Z must be on).     \n"
  "                                                                         \n"
  "      -S, --save-model             save models after learning,           \n"
  "      -L, --load-model             load models previously saved model,   \n"
  "      -M, --model-file <file>      model filename,                       \n"
  "      -I, --model-info             model info,                           \n"
  "                                                                         \n"
  "      -T, --train-model            train model only (no inference),      \n"
  "                                   (Attention!) Is expected to only receive \n"
  "                                   the first file group (FASTQ)             \n"
  "                                                                         \n"
  "      Mandatory arguments:                                               \n"
  "                                                                         \n"
  "      [FILE1]:[FILE2]:...  metagenomic filename (FASTQ),                 \n"
  "                           Use \":\" for splitting files.                \n"
  "                                                                         \n"
  "      [FILE1]:[FILE2]:...  database filename (Multi-FASTA).              \n"
  "                           Use \":\" for splitting files.                \n"
  "                                                                         \n"
  "                                                                         \n"
  "      MAGNET integration:                                                \n"
  "                                                                         \n"
  "      -mg, --magnet                enable MAGNET filtering,              \n"
  "                                                                         \n"
  "      Mandatory arguments:                                               \n"
  "                                                                         \n"
  "      -mf, --magnet-filter <file>  FASTA reference for filtering,        \n"
  "                                                                         \n"
  "      Non-mandatory arguments:                                           \n"
  "                                                                         \n"
  "      -mv, --magnet-verbose        verbose mode (more information),      \n"
  "      -mt <val>                    similarity threshold [0.0;1.0] (default: 0.9),\n"
  "      -ml <val>                    sensitivity level [1;44] (default: 36),       \n"
  "      -mi, --magnet-invert         invert filter,                                \n"
  "      -mp <val>                    portion of acceptance (default: 1),           \n"
  "                                                                         \n"
  "                                                                         \n"
  "COPYRIGHT                                                                \n"
  "      Copyright (C) 2014-2025, IEETA, University of Aveiro.              \n"
  "      This is a Free software, under GPLv3. You may redistribute         \n"
  "      copies of it under the terms of the GNU - General Public           \n"
  "      License v3 <http://www.gnu.org/licenses/gpl.html>.                 \n"
  "                                                                         \n",
  VERSION, RELEASE, (uint32_t) MIN_LEV, (uint32_t) MAX_LEV, (uint32_t) 
  DEFAULT_SAMPLE, (uint32_t) DEF_TOP, (uint32_t) DEFAULT_THREADS);
  }

void PrintMenuFilter(void){
  fprintf(stderr,
  "                                                                         \n"
  "      ███████╗ █████╗ ██╗      ██████╗ ██████╗ ███╗   ██╗██████╗         \n"
  "      ██╔════╝██╔══██╗██║     ██╔════╝██╔═══██╗████╗  ██║╚════██╗        \n"
  "      █████╗  ███████║██║     ██║     ██║   ██║██╔██╗ ██║ █████╔╝        \n"
  "      ██╔══╝  ██╔══██║██║     ██║     ██║   ██║██║╚██╗██║██╔═══╝         \n"
  "      ██║     ██║  ██║███████╗╚██████╗╚██████╔╝██║ ╚████║███████╗        \n"
  "      ╚═╝     ╚═╝  ╚═╝╚══════╝ ╚═════╝ ╚═════╝ ╚═╝  ╚═══╝╚══════╝        \n"
  "                                                                         \n"
  "NAME                                                                     \n"
  "      FALCON2 filter v%u.%u: a FALCON redundancy analysis tool.          \n"
  "                                                                         \n"
  "SYNOPSIS                                                                 \n"
  "      FALCON2 filter [OPTION]... [FILE]                                  \n"
  "                                                                         \n"
  "SAMPLE                                                                   \n"
  "      FALCON2 filter -v -F -t 1.0 -o seg.txt pro.com                     \n"
  "                                                                         \n"
  "DESCRIPTION                                                              \n"
  "      It filter and segments regions identified by FALCON.               \n"
  "      It estimates de redundancy of each segmented region.               \n"
  "      The input is provided by the output of FALCON (-y).                \n"
  "                                                                         \n"
  "      Non-mandatory arguments:                                           \n"
  "                                                                         \n"
  "      -h                     give this help,                             \n"
  "      -F                     force mode (overwrites top file),           \n"
  "      -V                     display version number,                     \n"
  "      -v                     verbose mode (more information),            \n"
  "                                                                         \n"
  "      -s  <size>             filter window size,                         \n"
  "      -w  <type>             filter window type,                         \n"
  "      -x  <sampling>         filter window sampling,                     \n"
  "      -sl <lower>            similarity lower bound,                     \n"
  "      -su <upper>            similarity upper bound,                     \n"
  "      -dl <lower>            size lower bound,                           \n"
  "      -du <upper>            size upper bound,                           \n"
  "      -t  <threshold>        threshold [0;2.0],                          \n"
  "                                                                         \n"
  "      -o  <FILE>             output segmented filename.                  \n"
  "                                                                         \n"
  "      Mandatory arguments:                                               \n"
  "                                                                         \n"
  "      [FILE]                 profile filename (from FALCON).            \n"
  "                                                                         \n"
  "COPYRIGHT                                                                \n"
  "      Copyright (C) 2014-2025, IEETA, University of Aveiro.              \n"
  "      This is a Free software, under GPLv3. You may redistribute         \n"
  "      copies of it under the terms of the GNU - General Public           \n"
  "      License v3 <http://www.gnu.org/licenses/gpl.html>.                 \n"
  "                                                                         \n",
  VERSION, RELEASE);
  }

void PrintMenuInter(void){
  fprintf(stderr,
  "                                                                         \n"
  "                                                                         \n"
  "      ███████╗ █████╗ ██╗      ██████╗ ██████╗ ███╗   ██╗██████╗         \n"
  "      ██╔════╝██╔══██╗██║     ██╔════╝██╔═══██╗████╗  ██║╚════██╗        \n"
  "      █████╗  ███████║██║     ██║     ██║   ██║██╔██╗ ██║ █████╔╝        \n"
  "      ██╔══╝  ██╔══██║██║     ██║     ██║   ██║██║╚██╗██║██╔═══╝         \n"
  "      ██║     ██║  ██║███████╗╚██████╗╚██████╔╝██║ ╚████║███████╗        \n"
  "      ╚═╝     ╚═╝  ╚═╝╚══════╝ ╚═════╝ ╚═════╝ ╚═╝  ╚═══╝╚══════╝        \n"
  "                                                                         \n"
  "NAME                                                                     \n"
  "      FALCON2 inter v%u.%u: a FALCON database analysis tool.             \n"
  "                                                                         \n"
  "SYNOPSIS                                                                 \n"
  "      FALCON2 inter [OPTION]... [FILE1]:[FILE2]:...                      \n"
  "                                                                         \n"
  "SAMPLE                                                                   \n"
  "      FALCON2 inter                                                      \n"
  "                                                                         \n"
  "DESCRIPTION                                                              \n"
  "      It evaluates the similarity of genomes identified by FALCON.       \n"
  "      It compares all the combinations of the identified genomes.        \n"
  "                                                                         \n"
  "      Non-mandatory arguments:                                           \n"
  "                                                                         \n"
  "      -h                   give this help,                               \n"
  "      -V                   display version number,                       \n"
  "      -v                   verbose mode (more information),              \n"
  "      -s                   how compression levels,                       \n"
  "      -l <level>           compression level [1;30],                     \n"
  "      -n <nThreads>        number of threads,                            \n"
  "      -x <FILE>            similarity matrix filename,                   \n"
  "      -o <FILE>            labels filename,                              \n"
  "                                                                         \n"
  "      Mandatory arguments:                                               \n"
  "                                                                         \n"
  "      [FILE]:[FILE]:[...]  input files (last arguments).                 \n"
  "                           Use \":\" for file splitting.                 \n"
  "                                                                         \n"
  "COPYRIGHT                                                                \n"
  "      Copyright (C) 2014-2025, IEETA, University of Aveiro.              \n"
  "      This is a Free software, under GPLv3. You may redistribute         \n"
  "      copies of it under the terms of the GNU - General Public           \n"
  "      License v3 <http://www.gnu.org/licenses/gpl.html>.                 \n"
  "                                                                         \n",
  VERSION, RELEASE);
  }

void PrintMenuVisual(void){
  fprintf(stderr,
  "                                                                         \n"
  "                                                                         \n"
  "      ███████╗ █████╗ ██╗      ██████╗ ██████╗ ███╗   ██╗██████╗         \n"
  "      ██╔════╝██╔══██╗██║     ██╔════╝██╔═══██╗████╗  ██║╚════██╗        \n"
  "      █████╗  ███████║██║     ██║     ██║   ██║██╔██╗ ██║ █████╔╝        \n"
  "      ██╔══╝  ██╔══██║██║     ██║     ██║   ██║██║╚██╗██║██╔═══╝         \n"
  "      ██║     ██║  ██║███████╗╚██████╗╚██████╔╝██║ ╚████║███████╗        \n"
  "      ╚═╝     ╚═╝  ╚═╝╚══════╝ ╚═════╝ ╚═════╝ ╚═╝  ╚═══╝╚══════╝        \n"
  "                                                                         \n"
  "NAME                                                                     \n"
  "      FALCON2 fvisual v%u.%u: a FALCON visualization tool.               \n"
  "                                                                         \n"
  "SYNOPSIS                                                                 \n"
  "      FALCON2 fvisual [OPTION]... [FILE]                                 \n"
  "                                                                         \n"
  "SAMPLE                                                                   \n"
  "      FALCON2 fvisual -v -F -o map.svg seg.txt                           \n"
  "                                                                         \n"
  "DESCRIPTION                                                              \n"
  "      It creates an SVG image according to the FALCON2 analysis.         \n"
  "      It depicts quantities and localizations of the regions.            \n"
  "                                                                         \n"
  "      Non-mandatory arguments:                                           \n"
  "                                                                         \n"
  "      -h                  give this help,                                \n"
  "      -F                  force mode (overwrites top file),              \n"
  "      -V                  display version number,                        \n"
  "      -v                  verbose mode (more information),               \n"
  "                                                                         \n"
  "      -w  <width>         square width (for each value),                 \n"
  "      -s  <ispace>        square inter-space (between each value),       \n"
  "      -i  <indexs>        color index start,                             \n"
  "      -r  <indexr>        color index rotations,                         \n"
  "      -u  <hue>           color hue,                                     \n"
  "      -sl <lower>         similarity lower bound,                        \n"
  "      -su <upper>         similarity upper bound,                        \n"
  "      -dl <lower>         size lower bound,                              \n"
  "      -du <upper>         size upper bound,                              \n"
  "      -g  <color>         color gamma,                                   \n"
  "      -e  <size>          enlarge painted regions,                       \n"
  "                                                                         \n"
  "      -bg                 show only the best of group,                   \n"
  "      -ss                 do NOT show global scale,                      \n"
  "      -sn                 do NOT show names,                             \n"
  "                                                                         \n"
  "      -o <FILE>           output image (SVG) filename.                   \n"
  "                                                                         \n"
  "      Mandatory arguments:                                               \n"
  "                                                                         \n"
  "      [FILE]              segmented filename (from FALCON-filter).       \n"
  "                                                                         \n"
  "COPYRIGHT                                                                \n"
  "      Copyright (C) 2014-2025, IEETA, University of Aveiro.              \n"
  "      This is a Free software, under GPLv3. You may redistribute         \n"
  "      copies of it under the terms of the GNU - General Public           \n"
  "      License v3 <http://www.gnu.org/licenses/gpl.html>.                 \n"
  "                                                                         \n",
  VERSION, RELEASE);
  }

void PrintMenuInterVisual(void){
  fprintf(stderr,
  "                                                                         \n"
  "      ███████╗ █████╗ ██╗      ██████╗ ██████╗ ███╗   ██╗██████╗         \n"
  "      ██╔════╝██╔══██╗██║     ██╔════╝██╔═══██╗████╗  ██║╚════██╗        \n"
  "      █████╗  ███████║██║     ██║     ██║   ██║██╔██╗ ██║ █████╔╝        \n"
  "      ██╔══╝  ██╔══██║██║     ██║     ██║   ██║██║╚██╗██║██╔═══╝         \n"
  "      ██║     ██║  ██║███████╗╚██████╗╚██████╔╝██║ ╚████║███████╗        \n"
  "      ╚═╝     ╚═╝  ╚═╝╚══════╝ ╚═════╝ ╚═════╝ ╚═╝  ╚═══╝╚══════╝        \n"
  "                                                                         \n"
  "NAME                                                                     \n"
  "      FALCON2 ivisual v%u.%u: a FALCON visualization tool.               \n"
  "                                                                         \n"
  "SYNOPSIS                                                                 \n"
  "      FALCON2 ivisual [OPTION]... [FILE]                                 \n"
  "                                                                         \n"
  "SAMPLE                                                                   \n"
  "      FALCON2 ivisual -F -l lab.txt -o mat.svg mat.txt                    \n"
  "                                                                         \n"
  "DESCRIPTION                                                              \n"
  "      It creates an SVG image according to FALCON-inter.                 \n"
  "      It depicts quantities for inter-similarity analysis.               \n"
  "                                                                         \n"
  "      Non-mandatory arguments:                                           \n"
  "                                                                         \n"
  "      -h             give this help,                                     \n"
  "      -V             display version number,                             \n"
  "      -v             verbose mode (more information),                    \n"
  "      -w             square width (for each value),                      \n"
  "      -a             square inter-space (between each value),            \n"
  "      -s             index color start,                                  \n"
  "      -r             index color rotations,                              \n"
  "      -u             color hue,                                          \n"
  "      -g             color gamma,                                        \n"
  "      -l <FILE>      labels filename,                                    \n"
  "      -x <FILE>      heatmap filename,                                   \n"
  "                                                                         \n"
  "      Mandatory arguments:                                               \n"
  "                                                                         \n"
  "      [FILE]         input matrix file (from FALCON inter).              \n"
  "                                                                         \n"
  "COPYRIGHT                                                                \n"
  "      Copyright (C) 2014-2025, IEETA, University of Aveiro.              \n"
  "      This is a Free software, under GPLv3. You may redistribute         \n"
  "      copies of it under the terms of the GNU - General Public           \n"
  "      License v3 <http://www.gnu.org/licenses/gpl.html>.                 \n"
  "                                                                         \n",
  VERSION, RELEASE);
  }

void PrintVersion(void){
  fprintf(stderr,
  "                                                                         \n"
  "      ███████╗ █████╗ ██╗      ██████╗ ██████╗ ███╗   ██╗██████╗         \n"
  "      ██╔════╝██╔══██╗██║     ██╔════╝██╔═══██╗████╗  ██║╚════██╗        \n"
  "      █████╗  ███████║██║     ██║     ██║   ██║██╔██╗ ██║ █████╔╝        \n"
  "      ██╔══╝  ██╔══██║██║     ██║     ██║   ██║██║╚██╗██║██╔═══╝         \n"
  "      ██║     ██║  ██║███████╗╚██████╗╚██████╔╝██║ ╚████║███████╗        \n"
  "      ╚═╝     ╚═╝  ╚═╝╚══════╝ ╚═════╝ ╚═════╝ ╚═╝  ╚═══╝╚══════╝        \n"
  "                                                                         \n"
  "                          VERSION %u.%u                                  \n"
  "                                                                         \n"
  "      An ultra-fast tool to infer metagenomic composition.               \n"
  "                                                                         \n"
  "      The FALCON2 package contains the following binaries:               \n"
  "                                                                         \n"
  "             # FALCON2 meta            INFERENCE                         \n"
  "             # FALCON2 filter          SEGMENTATION                      \n"
  "             # FALCON2 fvisual         FILT. VISUAL.                     \n"
  "             # FALCON2 inter           EVALUATION                        \n"
  "             # FALCON2 ivisual         EVAL. VISUAL.                     \n"
  "                                                                         \n"
  "                           AUTHORS:                                      \n"
  "                                                                         \n"
  "               Luís Laranjeira    lclm@ua.pt                             \n"
  "               Diogo Pratas       pratas@ua.pt                           \n"
  "               Armando Pinho      ap@ua.pt                               \n"
  "                                                                         \n"
  "         Copyright (C) 2014-2025 University of Aveiro.                   \n"
  "                                                                         \n"
  "            This is a Free software, under GPLv3.                        \n"
  "                                                                         \n"
  "You may redistribute copies of it under the terms of the GNU -           \n"
  "General Public License v3 <http://www.gnu.org/licenses/gpl.html>.        \n"
  "There is NOT ANY WARRANTY, to the extent permitted by law.               \n"
  "                                                                         \n", 
  VERSION, RELEASE);
  }

void PrintMagnetVersion(void){
  fprintf(stderr,
  "                                                                         \n"
  "                          ===================                            \n"
  "                          |   MAGNET %u.%u  |                            \n"
  "                          ===================                            \n"
  "                                                                         \n"
  "                An ultra-fast and high-sensitive tool to                 \n"
  "                     filter specific DNA content.                        \n"
  "                                                                         \n"
  "              Copyright (C) 2014-2025 University of Aveiro.              \n"
  "                                                                         \n"
  "                  This is a Free software, under GPLv3.                  \n"
  "                                                                         \n"
  "You may redistribute copies of it under the terms of the GNU - General   \n"
  "Public License v3 <http://www.gnu.org/licenses/gpl.html>. There is NOT   \n"
  "ANY WARRANTY, to the extent permitted by law. Developed and Written by   \n"
  "Diogo Pratas.\n\n", (uint32_t) MAGNET_VERSION, (uint32_t) MAGNET_RELEASE);
}
